# remote_theme: pages-themes/minimal@v0.2.0
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Monkey Auth - Documentation
description: Monkey Auth is a simple and secure authentication system for your web applications.

sidebar:
  - getting-started
  - label: Dev Docs
    children:
      - doc-1
      - doc-2
  - deployment
